export const People = [
    {
      token: 'aeACMoa9dladUCMWaldd',
      code: 1,
      name: 'Oscar',
      last_name: 'Rodriguez',
      email: 'oara@gmail.com',
      password: 'pass1',
      rol: 1,
      status: true,
    },
    {
      token: 'JkLamNNaOiaSlMuYaQs',
      code: 2,
      name: 'Ivette',
      last_name: 'Pinto',
      email: 'ivettepinto@gmail.com',
      password: 'pass2',
      rol: 2,
      status: true,
    },
    {
      token: 'QQESITwrvslfjSmcooSOP',
      code: 3,
      name: 'Oscar',
      last_name: 'Recinos',
      email: 'orecinos@gmail.com',
      password: 'pass3',
      rol: 3,
      status: true,
    },
    {
      token: 'TUAOFakdrmbirp74d9ussetvv',
      code: 4,
      name: 'Juana',
      last_name: 'Juarez',
      email: 'jjuarez@gmail.com',
      password: 'pass4',
      rol: 4,
      status: true,
    },
    {
      token: 'sUaQOzFsap174d9ussdetvv',
      code: 5,
      name: 'Jose',
      last_name: 'Jose',
      email: 'josejose@gmail.com',
      password: 'pass5',
      rol: 2,
      status: false,
    }
  ]